name: todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable:
  hive:
  hive_flutter:
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
